name: ${PROJECT_NAME}
services:
  develop:
    hostname: develop
    build:
      context: .
      dockerfile: ./docker/dev/app.Dockerfile
      args:
        - DEV_CONTAINER_UID=${DEV_CONTAINER_UID}
        - DEV_CONTAINER_GID=${DEV_CONTAINER_GID}
    volumes:
      - ".:/home/dev/code"
      - ".devcontainer/.bash_history:/home/dev/.bash_history"
    env_file:
      - ./.env
    ports:
      - 4321:4321
